### PR TITLE
[WIP] Updated version of post installation script

### PR DESCRIPTION
**Pull request by ipa-nhg**
This PR substitute the https://github.com/ipa320/setup_cob4/pull/130 and https://github.com/ipa320/setup_cob4/pull/107

Includes also the mimic setup and upstart installation. Once is merged setup_cob4 repository can be cleaned

### CODE REVIEW

**Comment by ipa-nhg** [comment]
Please do not merge, has to be tested on a real robot

**Comment by ipa-bnm** [comment]
On custom configuration the `camera_client_list` inside `/usr/sbin/cob-start` isn't updated correctly.

**Comment by ipa-nhg** [comment]
didn't work because https://github.com/ipa320/setup_cob4/pull/107/files is required, I will join both PRs

**Comment by ipa-fmw** [comment]
merged #107

**Pull request merged**
