### PR TITLE
additional packages

### PR DESCRIPTION
**Pull request by ipa-fxm**
also contributes to #170 

@ipa-fmw @ipa-nhg @ipa-bnm 
is this the correct spot to add additional packages? do I need to add something anywhere else?

### CODE REVIEW

**Comment by ipa-fmw** [comment]
this is the correct spot for all apt-packages we'd like to have installed on our robots which are __not__ dependencies of ROS packages.

Thus I'm unsure for `default-jdk`, the rest of the packages is OK.

**Comment by ipa-fxm** [comment]
`openjdk-6-jdk` was giving us problems during `innorobo`...`openjdk-7-jdk` worked...`default-jdk` maps to `default-jdk`

**Comment by ipa-fmw** [comment]
but this should be a dependency of voice_control and gets installed via `rosdep install`, right? so we can delete it here.

**Comment by ipa-fxm** [comment]
yes we can use [`java`](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L1212) in the package.xml

**Comment by ipa-fxm** [comment]
updated java dependency handling here and in https://github.com/unity-robotics/msh_voice_control/pull/14

**Pull request merged**
