### PR TITLE
New cob-command

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
thanks @ipa-fxm for your suggestions

**Comment by ipa-fxm** [comment]
as discussed with @ipa-nhg in person:
I'd suggest to provide one PR combining all fixes/changes made by @ipa-nhg throughout the last few days fixing the various setup issues...e.g. please merge #94 #95 #97 #98 #99 into this PR  #96
this way we make sure they are properly merged...

I think this is better to test the whole shebang together rather than individually

**Comment by ipa-fmw** [comment]
can be tested with the following commands: https://github.com/ipa320/setup_cob4/pull/76#issuecomment-292560163

**Comment by fmw-hb** [comment]
The colors are a little bit dark for a black terminal-background.

```
fmw-hb@cob4-7-b1:~$ sudo cob-command ls -v
===========================================
Listing sessions....
===========================================

 
error: improper list

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
bringup
  pc: 10.4.7.11
  user: msh
  PID: 
  command: 
error: improper list

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
roscore
  pc: 10.4.7.11
  user: msh
  PID: 
  command: 
sm
  pc: 10.4.7.21
  user: msh
  PID: 
  command: 
```
(same improper list error for `ls` only)

```
fmw-hb@cob4-7-b1:~$ sudo cob-command find sm
===========================================
Finding sessions....
===========================================

 
no session name defined
```
(tried with `"sm"` and `'sm'` as well)

**Comment by fmw-hb** [comment]
Furthermore, calling `sudo cob-command stop -a` did kill the roscore, too (which is not the intended functionality as far as I am concerned)

**Comment by ipa-fmw** [comment]
not mergable and replaced with https://github.com/ipa320/setup_cob4/pull/105

**Pull request closed without merging**
