### PR TITLE
Update cob-shutdown

### PR DESCRIPTION
**Pull request by ipa-nhg**
has to be tested, sometimes the robot needs too long to shutdown the base pc..

### CODE REVIEW

**Comment by ipa-fmw** [comment]
does this hardly cut off power from the pc? if yes, then we should avoid that and properly shutdown processes with possible disk-IO read/writes.

**Comment by ipa-nhg** [comment]
sorry, I meant without the "-f" . The poweroff man says:


`When called with --force or when in runlevel 0 or 6, this tool invokes the reboot(2) system call itself and directly reboots the system. Otherwise this simply invokes the shutdown(8) tool with the appropriate arguments.`


lets check what means **with the appropriate arguments**

**Comment by ipa-fxm** [comment]
What's it with this PR?
Do we still need this? Or is the current behavior (without this PR) acceptable)? @ipa-nhg please close then

**Comment by ipa-fmw** [comment]
I'd like to not merge this one

**Pull request closed without merging**
