### PR TITLE
simplify upstart installation

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-fmw** [comment]
is this still relevant with #55 being merged?

**Comment by ipa-nhg** [comment]
yes, this has nothing to do with the cob-start script

**Comment by ipa-fxm** [comment]
in which order to we have to test/merge these PRs?  #80, #76, #61, #52
@ipa-nhg could you combine them into one and resolve merge conflicts?

**Comment by ipa-nhg** [comment]
This is already out-of-date , close!

**Pull request closed without merging**
